### ISSUE TITLE
[質問]APIにRESTでなくGraphQLを利用した理由

### ISSUE THREAD

**Issue by nmikuni** [yuuu/iot_dashboard_aws_amplify_book_site#4]
GraphQLを書いたことがなかったため、非常に勉強になりました。
普段RESTを使っているため、RESTで同様な構成を作ってみようかなと考えているのですが、もしRESTでなくGraphQLを選択した理由があらば、教えていただきたいです。
デバイスの新規登録、編集、削除をLambdaなしにReactのhooksで出来ることがひとつのメリットかなと考えているのですが、他にもあるようでしたら伺いたいです。

**Comment by yuuu** [comment]
@nmikuni 
質問ありがとうございます。気づくのが遅れてしまい申し訳ありません。

GraphQLを選択した理由についてはいくつかあります。

- Amplifyのデータモデリングの仕組みが充実しており、リソース同士の関連をスキーマベースで定義できる
    - 参考: https://docs.amplify.aws/cli/graphql/data-modeling/
- Amplify CLIがクライアントコードを自動生成してくれるので、よりスピーディーにプロダクト構築できる
- フロントエンド側で取得する属性を取捨選択できる
    - 本書ではこのメリットが活きる場面はあまりなかったですが
- APIを増やそうとしたときにLambda関数を増やさずに済む

おっしゃるとおり、証明書の作成やデバイスの作成ではフロントエンドとAppSyncの間にLambdaを挟む構造となり、その部分の構築は手間がかかる部分なので、割り切ってRESTを使うのも手だと思います。RESTであればreact-queryやSWRといったクライアントも活用できる点も良いですね 👍

**Comment by nmikuni** [comment]
ありがとうございます！大変勉強になりました。自動生成やモデリングは強力ですね。
